// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/camera.dart';
import 'api/export.dart';
import 'api/lighting.dart';
import 'api/measurement.dart';
import 'api/models.dart';
import 'api/overlay.dart';
import 'api/properties.dart';
import 'api/rendering.dart';
import 'api/section.dart';
import 'api/selection.dart';
import 'api/state.dart';
import 'api/system.dart';
import 'bim/entities.dart';
import 'bim/geometry.dart';
import 'bim/model.dart';
import 'bim/model_registry.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, Int32List> dco_decode_Map_String_list_prim_i_32_strict_None(dynamic raw);

  @protected
  Map<String, BigInt> dco_decode_Map_String_usize_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BoundingBox dco_decode_bounding_box(dynamic raw);

  @protected
  ElementInfo dco_decode_box_autoadd_element_info(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  GeoReference dco_decode_box_autoadd_geo_reference(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  MaterialData dco_decode_box_autoadd_material_data(dynamic raw);

  @protected
  TypeObjectData dco_decode_box_autoadd_type_object_data(dynamic raw);

  @protected
  ColorMode dco_decode_color_mode(dynamic raw);

  @protected
  ElementInfo dco_decode_element_info(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  F32Array3 dco_decode_f_32_array_3(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GeoReference dco_decode_geo_reference(dynamic raw);

  @protected
  GridLine dco_decode_grid_line(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ElementInfo> dco_decode_list_element_info(dynamic raw);

  @protected
  List<GridLine> dco_decode_list_grid_line(dynamic raw);

  @protected
  List<MaterialLayerData> dco_decode_list_material_layer_data(dynamic raw);

  @protected
  List<MeasurementPoint> dco_decode_list_measurement_point(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PropertyInfo> dco_decode_list_property_info(dynamic raw);

  @protected
  List<PropertySetInfo> dco_decode_list_property_set_info(dynamic raw);

  @protected
  List<(String, Int32List)> dco_decode_list_record_string_list_prim_i_32_strict(dynamic raw);

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_usize(dynamic raw);

  @protected
  List<RegisteredModelInfo> dco_decode_list_registered_model_info(dynamic raw);

  @protected
  List<SpatialNode> dco_decode_list_spatial_node(dynamic raw);

  @protected
  MaterialData dco_decode_material_data(dynamic raw);

  @protected
  MaterialLayerData dco_decode_material_layer_data(dynamic raw);

  @protected
  MeasurementPoint dco_decode_measurement_point(dynamic raw);

  @protected
  MeasurementResult dco_decode_measurement_result(dynamic raw);

  @protected
  ModelInfo dco_decode_model_info(dynamic raw);

  @protected
  ModelStats dco_decode_model_stats(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ElementInfo? dco_decode_opt_box_autoadd_element_info(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  GeoReference? dco_decode_opt_box_autoadd_geo_reference(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  MaterialData? dco_decode_opt_box_autoadd_material_data(dynamic raw);

  @protected
  TypeObjectData? dco_decode_opt_box_autoadd_type_object_data(dynamic raw);

  @protected
  PropertyInfo dco_decode_property_info(dynamic raw);

  @protected
  PropertySetInfo dco_decode_property_set_info(dynamic raw);

  @protected
  (String, Int32List) dco_decode_record_string_list_prim_i_32_strict(dynamic raw);

  @protected
  (String, BigInt) dco_decode_record_string_usize(dynamic raw);

  @protected
  RegisteredModelInfo dco_decode_registered_model_info(dynamic raw);

  @protected
  RenderStats dco_decode_render_stats(dynamic raw);

  @protected
  SpatialNode dco_decode_spatial_node(dynamic raw);

  @protected
  TypeObjectData dco_decode_type_object_data(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Map<String, Int32List> sse_decode_Map_String_list_prim_i_32_strict_None(SseDeserializer deserializer);

  @protected
  Map<String, BigInt> sse_decode_Map_String_usize_None(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BoundingBox sse_decode_bounding_box(SseDeserializer deserializer);

  @protected
  ElementInfo sse_decode_box_autoadd_element_info(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GeoReference sse_decode_box_autoadd_geo_reference(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  MaterialData sse_decode_box_autoadd_material_data(SseDeserializer deserializer);

  @protected
  TypeObjectData sse_decode_box_autoadd_type_object_data(SseDeserializer deserializer);

  @protected
  ColorMode sse_decode_color_mode(SseDeserializer deserializer);

  @protected
  ElementInfo sse_decode_element_info(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  F32Array3 sse_decode_f_32_array_3(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GeoReference sse_decode_geo_reference(SseDeserializer deserializer);

  @protected
  GridLine sse_decode_grid_line(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ElementInfo> sse_decode_list_element_info(SseDeserializer deserializer);

  @protected
  List<GridLine> sse_decode_list_grid_line(SseDeserializer deserializer);

  @protected
  List<MaterialLayerData> sse_decode_list_material_layer_data(SseDeserializer deserializer);

  @protected
  List<MeasurementPoint> sse_decode_list_measurement_point(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PropertyInfo> sse_decode_list_property_info(SseDeserializer deserializer);

  @protected
  List<PropertySetInfo> sse_decode_list_property_set_info(SseDeserializer deserializer);

  @protected
  List<(String, Int32List)> sse_decode_list_record_string_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_usize(SseDeserializer deserializer);

  @protected
  List<RegisteredModelInfo> sse_decode_list_registered_model_info(SseDeserializer deserializer);

  @protected
  List<SpatialNode> sse_decode_list_spatial_node(SseDeserializer deserializer);

  @protected
  MaterialData sse_decode_material_data(SseDeserializer deserializer);

  @protected
  MaterialLayerData sse_decode_material_layer_data(SseDeserializer deserializer);

  @protected
  MeasurementPoint sse_decode_measurement_point(SseDeserializer deserializer);

  @protected
  MeasurementResult sse_decode_measurement_result(SseDeserializer deserializer);

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer);

  @protected
  ModelStats sse_decode_model_stats(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ElementInfo? sse_decode_opt_box_autoadd_element_info(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GeoReference? sse_decode_opt_box_autoadd_geo_reference(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  MaterialData? sse_decode_opt_box_autoadd_material_data(SseDeserializer deserializer);

  @protected
  TypeObjectData? sse_decode_opt_box_autoadd_type_object_data(SseDeserializer deserializer);

  @protected
  PropertyInfo sse_decode_property_info(SseDeserializer deserializer);

  @protected
  PropertySetInfo sse_decode_property_set_info(SseDeserializer deserializer);

  @protected
  (String, Int32List) sse_decode_record_string_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  (String, BigInt) sse_decode_record_string_usize(SseDeserializer deserializer);

  @protected
  RegisteredModelInfo sse_decode_registered_model_info(SseDeserializer deserializer);

  @protected
  RenderStats sse_decode_render_stats(SseDeserializer deserializer);

  @protected
  SpatialNode sse_decode_spatial_node(SseDeserializer deserializer);

  @protected
  TypeObjectData sse_decode_type_object_data(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_list_prim_i_32_strict_None(Map<String, Int32List> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_usize_None(Map<String, BigInt> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bounding_box(BoundingBox self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_element_info(ElementInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_geo_reference(GeoReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_material_data(MaterialData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_type_object_data(TypeObjectData self, SseSerializer serializer);

  @protected
  void sse_encode_color_mode(ColorMode self, SseSerializer serializer);

  @protected
  void sse_encode_element_info(ElementInfo self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_32_array_3(F32Array3 self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_geo_reference(GeoReference self, SseSerializer serializer);

  @protected
  void sse_encode_grid_line(GridLine self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_element_info(List<ElementInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_grid_line(List<GridLine> self, SseSerializer serializer);

  @protected
  void sse_encode_list_material_layer_data(List<MaterialLayerData> self, SseSerializer serializer);

  @protected
  void sse_encode_list_measurement_point(List<MeasurementPoint> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(Float32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_strict(Int32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_property_info(List<PropertyInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_property_set_info(List<PropertySetInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_list_prim_i_32_strict(List<(String, Int32List)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_usize(List<(String, BigInt)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_registered_model_info(List<RegisteredModelInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_spatial_node(List<SpatialNode> self, SseSerializer serializer);

  @protected
  void sse_encode_material_data(MaterialData self, SseSerializer serializer);

  @protected
  void sse_encode_material_layer_data(MaterialLayerData self, SseSerializer serializer);

  @protected
  void sse_encode_measurement_point(MeasurementPoint self, SseSerializer serializer);

  @protected
  void sse_encode_measurement_result(MeasurementResult self, SseSerializer serializer);

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer);

  @protected
  void sse_encode_model_stats(ModelStats self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_element_info(ElementInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_geo_reference(GeoReference? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_material_data(MaterialData? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_type_object_data(TypeObjectData? self, SseSerializer serializer);

  @protected
  void sse_encode_property_info(PropertyInfo self, SseSerializer serializer);

  @protected
  void sse_encode_property_set_info(PropertySetInfo self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_list_prim_i_32_strict((String, Int32List) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_usize((String, BigInt) self, SseSerializer serializer);

  @protected
  void sse_encode_registered_model_info(RegisteredModelInfo self, SseSerializer serializer);

  @protected
  void sse_encode_render_stats(RenderStats self, SseSerializer serializer);

  @protected
  void sse_encode_spatial_node(SpatialNode self, SseSerializer serializer);

  @protected
  void sse_encode_type_object_data(TypeObjectData self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) => RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;
}
