// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base_url`, `build_request`, `default_headers`, `endpoints`, `project_url`, `require_config`, `with_api_config`, `with_bcf`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ApiComment`, `ApiTopic`, `BcfApiConfig`, `BcfApiEndpoints`, `BcfApiRequest`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Create a new BCF project, replacing any existing one. Returns the project ID.
String createBcfProject({required String name}) => RustLib.instance.api.crateApiBcfCreateBcfProject(name: name);

/// Clear the current BCF project.
void clearBcfProject() => RustLib.instance.api.crateApiBcfClearBcfProject();

/// Get the number of topics in the current BCF project.
int getTopicCount() => RustLib.instance.api.crateApiBcfGetTopicCount();

/// Create a new BCF topic. Returns the topic GUID.
String createBcfTopic({required String title, required String description, required String topicType}) =>
    RustLib.instance.api.crateApiBcfCreateBcfTopic(title: title, description: description, topicType: topicType);

/// Delete a topic by GUID.
void deleteTopic({required String topicGuid}) => RustLib.instance.api.crateApiBcfDeleteTopic(topicGuid: topicGuid);

/// Get all topics as summaries.
List<BcfTopicSummary> getAllTopics() => RustLib.instance.api.crateApiBcfGetAllTopics();

/// Get full detail for a single topic.
BcfTopicDetail getTopicDetail({required String topicGuid}) =>
    RustLib.instance.api.crateApiBcfGetTopicDetail(topicGuid: topicGuid);

/// Set topic status. 0=Open, 1=InProgress, 2=Closed, 3=ReOpened.
void setTopicStatus({required String topicGuid, required int status}) =>
    RustLib.instance.api.crateApiBcfSetTopicStatus(topicGuid: topicGuid, status: status);

/// Set topic priority. 0=Low, 1=Normal, 2=High, 3=Critical.
void setTopicPriority({required String topicGuid, required int priority}) =>
    RustLib.instance.api.crateApiBcfSetTopicPriority(topicGuid: topicGuid, priority: priority);

/// Set the assigned-to field on a topic.
void setTopicAssignedTo({required String topicGuid, required String assignedTo}) =>
    RustLib.instance.api.crateApiBcfSetTopicAssignedTo(topicGuid: topicGuid, assignedTo: assignedTo);

/// Add a comment to a topic. Returns the comment GUID.
String addBcfComment({required String topicGuid, required String author, required String text}) =>
    RustLib.instance.api.crateApiBcfAddBcfComment(topicGuid: topicGuid, author: author, text: text);

/// Capture the current camera position, selection, and hidden elements as a
/// BCF viewpoint and attach it to the specified topic. Returns the viewpoint GUID.
String createViewpointFromCurrent({required String topicGuid}) =>
    RustLib.instance.api.crateApiBcfCreateViewpointFromCurrent(topicGuid: topicGuid);

/// Navigate to a BCF viewpoint: restore camera position/target and apply
/// selection/visibility state.
void navigateToViewpoint({required String topicGuid, required String viewpointGuid}) =>
    RustLib.instance.api.crateApiBcfNavigateToViewpoint(topicGuid: topicGuid, viewpointGuid: viewpointGuid);

/// Export the current BCF project as BCF 2.1 ZIP bytes.
Uint8List exportBcfToBytes() => RustLib.instance.api.crateApiBcfExportBcfToBytes();

/// Import a BCF 2.1 ZIP from bytes, replacing the current project.
/// Returns the number of topics imported.
int importBcfFromBytes({required List<int> data}) => RustLib.instance.api.crateApiBcfImportBcfFromBytes(data: data);

/// Export the current BCF project as BCF 3.0 JSON string.
String exportBcfJsonString() => RustLib.instance.api.crateApiBcfExportBcfJsonString();

/// Import a BCF 3.0 JSON string, replacing the current project.
/// Returns the number of topics imported.
int importBcfJsonString({required String json}) => RustLib.instance.api.crateApiBcfImportBcfJsonString(json: json);

/// Configure the BCF API server URL and version.
void configureBcfServer({required String serverUrl, required String apiVersion}) =>
    RustLib.instance.api.crateApiBcfConfigureBcfServer(serverUrl: serverUrl, apiVersion: apiVersion);

/// Set the Bearer auth token for the BCF API server.
void setBcfAuthToken({required String token}) => RustLib.instance.api.crateApiBcfSetBcfAuthToken(token: token);

/// Clear the Bearer auth token.
void clearBcfAuthToken() => RustLib.instance.api.crateApiBcfClearBcfAuthToken();

/// Set the project ID used for all subsequent API requests.
void setBcfProject({required String projectId}) => RustLib.instance.api.crateApiBcfSetBcfProject(projectId: projectId);

/// Return the current BCF API configuration as JSON.
String getBcfConfig() => RustLib.instance.api.crateApiBcfGetBcfConfig();

/// Build a request to list all topics for the configured project.
String buildListTopicsRequest() => RustLib.instance.api.crateApiBcfBuildListTopicsRequest();

/// Build a request to get a single topic by GUID.
String buildGetTopicRequest({required String topicGuid}) =>
    RustLib.instance.api.crateApiBcfBuildGetTopicRequest(topicGuid: topicGuid);

/// Build a request to create a new topic.
String buildCreateTopicRequest(
        {required String title,
        required String description,
        required String topicType,
        required String priority,
        required String status}) =>
    RustLib.instance.api.crateApiBcfBuildCreateTopicRequest(
        title: title, description: description, topicType: topicType, priority: priority, status: status);

/// Build a request to update an existing topic. `updates_json` is a JSON
/// object with the fields to patch (e.g. `{"title":"new","priority":"High"}`).
String buildUpdateTopicRequest({required String topicGuid, required String updatesJson}) =>
    RustLib.instance.api.crateApiBcfBuildUpdateTopicRequest(topicGuid: topicGuid, updatesJson: updatesJson);

/// Build a request to list comments for a topic.
String buildListCommentsRequest({required String topicGuid}) =>
    RustLib.instance.api.crateApiBcfBuildListCommentsRequest(topicGuid: topicGuid);

/// Build a request to create a comment on a topic.
String buildCreateCommentRequest({required String topicGuid, required String comment}) =>
    RustLib.instance.api.crateApiBcfBuildCreateCommentRequest(topicGuid: topicGuid, comment: comment);

/// Build a request to list viewpoints for a topic.
String buildListViewpointsRequest({required String topicGuid}) =>
    RustLib.instance.api.crateApiBcfBuildListViewpointsRequest(topicGuid: topicGuid);

/// Build a request to create a viewpoint on a topic. `viewpoint_json` is the
/// BCF viewpoint payload (camera, components, etc.).
String buildCreateViewpointRequest({required String topicGuid, required String viewpointJson}) =>
    RustLib.instance.api.crateApiBcfBuildCreateViewpointRequest(topicGuid: topicGuid, viewpointJson: viewpointJson);

/// Parse a BCF API topics list response. Returns our internal `BcfTopic[]` as JSON.
String parseTopicsResponse({required String responseJson}) =>
    RustLib.instance.api.crateApiBcfParseTopicsResponse(responseJson: responseJson);

/// Parse a BCF API comments list response. Returns our internal `BcfComment[]` as JSON.
String parseCommentsResponse({required String responseJson}) =>
    RustLib.instance.api.crateApiBcfParseCommentsResponse(responseJson: responseJson);

/// Import topics from a BCF API topics list response JSON into the local BCF
/// store, creating a project if none exists. Returns the number of topics imported.
BigInt syncTopicsFromResponse({required String responseJson}) =>
    RustLib.instance.api.crateApiBcfSyncTopicsFromResponse(responseJson: responseJson);

/// Prepare all local topics as BCF API-compatible JSON, ready for upload.
/// Returns a JSON array of topic objects matching the API schema.
String prepareTopicsForUpload() => RustLib.instance.api.crateApiBcfPrepareTopicsForUpload();

/// Comment data for Flutter.
class BcfCommentData {
  final String guid;
  final String date;
  final String author;
  final String text;
  final String? viewpointGuid;

  const BcfCommentData({
    required this.guid,
    required this.date,
    required this.author,
    required this.text,
    this.viewpointGuid,
  });

  @override
  int get hashCode => guid.hashCode ^ date.hashCode ^ author.hashCode ^ text.hashCode ^ viewpointGuid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BcfCommentData &&
          runtimeType == other.runtimeType &&
          guid == other.guid &&
          date == other.date &&
          author == other.author &&
          text == other.text &&
          viewpointGuid == other.viewpointGuid;
}

/// Full detail of a BCF topic including comments.
class BcfTopicDetail {
  final String guid;
  final String title;
  final String description;
  final String status;
  final String priority;
  final String topicType;
  final String creationDate;
  final String creationAuthor;
  final String? modifiedDate;
  final String? assignedTo;
  final List<BcfCommentData> comments;
  final int viewpointCount;

  const BcfTopicDetail({
    required this.guid,
    required this.title,
    required this.description,
    required this.status,
    required this.priority,
    required this.topicType,
    required this.creationDate,
    required this.creationAuthor,
    this.modifiedDate,
    this.assignedTo,
    required this.comments,
    required this.viewpointCount,
  });

  @override
  int get hashCode =>
      guid.hashCode ^
      title.hashCode ^
      description.hashCode ^
      status.hashCode ^
      priority.hashCode ^
      topicType.hashCode ^
      creationDate.hashCode ^
      creationAuthor.hashCode ^
      modifiedDate.hashCode ^
      assignedTo.hashCode ^
      comments.hashCode ^
      viewpointCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BcfTopicDetail &&
          runtimeType == other.runtimeType &&
          guid == other.guid &&
          title == other.title &&
          description == other.description &&
          status == other.status &&
          priority == other.priority &&
          topicType == other.topicType &&
          creationDate == other.creationDate &&
          creationAuthor == other.creationAuthor &&
          modifiedDate == other.modifiedDate &&
          assignedTo == other.assignedTo &&
          comments == other.comments &&
          viewpointCount == other.viewpointCount;
}

/// Summary of a BCF topic for list views.
class BcfTopicSummary {
  final String guid;
  final String title;
  final String status;
  final String priority;
  final int commentCount;
  final String creationDate;

  const BcfTopicSummary({
    required this.guid,
    required this.title,
    required this.status,
    required this.priority,
    required this.commentCount,
    required this.creationDate,
  });

  @override
  int get hashCode =>
      guid.hashCode ^
      title.hashCode ^
      status.hashCode ^
      priority.hashCode ^
      commentCount.hashCode ^
      creationDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BcfTopicSummary &&
          runtimeType == other.runtimeType &&
          guid == other.guid &&
          title == other.title &&
          status == other.status &&
          priority == other.priority &&
          commentCount == other.commentCount &&
          creationDate == other.creationDate;
}
