// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Orbit the camera around the target
void orbitCamera({required double deltaX, required double deltaY}) =>
    RustLib.instance.api.crateApiCameraOrbitCamera(deltaX: deltaX, deltaY: deltaY);

/// Zoom the camera in/out
void zoomCamera({required double delta}) => RustLib.instance.api.crateApiCameraZoomCamera(delta: delta);

/// Fit camera to current model bounds (primary model)
void fitCameraToModel() => RustLib.instance.api.crateApiCameraFitCameraToModel();

/// Fit camera to all visible models
void fitCameraToAllModels() => RustLib.instance.api.crateApiCameraFitCameraToAllModels();
