// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_summary`, `clash_result_to_info`, `store_report`, `with_report`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Run clash detection across all visible models with the given tolerances.
///
/// Stores results internally; query them with `get_clash_results()`.
ClashSummary runClashDetection(
        {required double hardTolerance,
        required double softTolerance,
        required double clearanceTolerance,
        required bool checkSameType}) =>
    RustLib.instance.api.crateApiClashRunClashDetection(
        hardTolerance: hardTolerance,
        softTolerance: softTolerance,
        clearanceTolerance: clearanceTolerance,
        checkSameType: checkSameType);

/// Run clash detection filtered to a specific pair of element types.
ClashSummary runClashDetectionFiltered({required String typeA, required String typeB, required double tolerance}) =>
    RustLib.instance.api.crateApiClashRunClashDetectionFiltered(typeA: typeA, typeB: typeB, tolerance: tolerance);

/// Return all clash results from the most recent detection run.
List<ClashInfo> getClashResults() => RustLib.instance.api.crateApiClashGetClashResults();

/// Return clashes filtered by group name.
List<ClashInfo> getClashesByGroup({required String groupName}) =>
    RustLib.instance.api.crateApiClashGetClashesByGroup(groupName: groupName);

/// Get total clash count from the last run.
int getClashCount() => RustLib.instance.api.crateApiClashGetClashCount();

/// Export the last clash report as a CSV string.
String exportClashCsv() => RustLib.instance.api.crateApiClashExportClashCsv();

/// Export the last clash report as an HTML string.
String exportClashHtml() => RustLib.instance.api.crateApiClashExportClashHtml();

/// Clear stored clash results.
void clearClashResults() => RustLib.instance.api.crateApiClashClearClashResults();

/// Navigate the camera to focus on a specific clash point.
///
/// Expands a small AABB around the clash point and calls
/// `fit_camera_to_bounds` on the renderer.
void navigateToClash({required int clashId}) => RustLib.instance.api.crateApiClashNavigateToClash(clashId: clashId);

/// Per-group clash counts.
class ClashGroupInfo {
  final String name;
  final int count;

  const ClashGroupInfo({
    required this.name,
    required this.count,
  });

  @override
  int get hashCode => name.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClashGroupInfo && runtimeType == other.runtimeType && name == other.name && count == other.count;
}

/// Simplified clash result for the Flutter bridge.
class ClashInfo {
  final int id;
  final int elementAId;
  final String elementAName;
  final String elementAType;
  final int elementBId;
  final String elementBName;
  final String elementBType;

  /// 0 = Hard, 1 = Soft, 2 = Clearance
  final int clashType;
  final double distance;
  final double pointX;
  final double pointY;
  final double pointZ;
  final String groupName;

  const ClashInfo({
    required this.id,
    required this.elementAId,
    required this.elementAName,
    required this.elementAType,
    required this.elementBId,
    required this.elementBName,
    required this.elementBType,
    required this.clashType,
    required this.distance,
    required this.pointX,
    required this.pointY,
    required this.pointZ,
    required this.groupName,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      elementAId.hashCode ^
      elementAName.hashCode ^
      elementAType.hashCode ^
      elementBId.hashCode ^
      elementBName.hashCode ^
      elementBType.hashCode ^
      clashType.hashCode ^
      distance.hashCode ^
      pointX.hashCode ^
      pointY.hashCode ^
      pointZ.hashCode ^
      groupName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClashInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          elementAId == other.elementAId &&
          elementAName == other.elementAName &&
          elementAType == other.elementAType &&
          elementBId == other.elementBId &&
          elementBName == other.elementBName &&
          elementBType == other.elementBType &&
          clashType == other.clashType &&
          distance == other.distance &&
          pointX == other.pointX &&
          pointY == other.pointY &&
          pointZ == other.pointZ &&
          groupName == other.groupName;
}

/// Summary of a clash detection run for the Flutter bridge.
class ClashSummary {
  final int totalClashes;
  final int hardClashes;
  final int softClashes;
  final int clearanceClashes;
  final List<ClashGroupInfo> groups;

  const ClashSummary({
    required this.totalClashes,
    required this.hardClashes,
    required this.softClashes,
    required this.clearanceClashes,
    required this.groups,
  });

  @override
  int get hashCode =>
      totalClashes.hashCode ^ hardClashes.hashCode ^ softClashes.hashCode ^ clearanceClashes.hashCode ^ groups.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClashSummary &&
          runtimeType == other.runtimeType &&
          totalClashes == other.totalClashes &&
          hardClashes == other.hardClashes &&
          softClashes == other.softClashes &&
          clearanceClashes == other.clearanceClashes &&
          groups == other.groups;
}
