// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compare_bounds`, `compare_elements`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ComparisonOverlay`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Compare two loaded models by matching elements via GlobalID.
///
/// Model A is treated as the "old" / baseline model.
/// Model B is treated as the "new" / updated model.
ComparisonResult compareModels({required String modelAId, required String modelBId}) =>
    RustLib.instance.api.crateApiComparisonCompareModels(modelAId: modelAId, modelBId: modelBId);

/// Get just the element IDs of elements added in model B.
Int32List getAddedElementIds({required String modelAId, required String modelBId}) =>
    RustLib.instance.api.crateApiComparisonGetAddedElementIds(modelAId: modelAId, modelBId: modelBId);

/// Get just the element IDs of elements removed from model A.
Int32List getRemovedElementIds({required String modelAId, required String modelBId}) =>
    RustLib.instance.api.crateApiComparisonGetRemovedElementIds(modelAId: modelAId, modelBId: modelBId);

/// Get just the new element IDs of modified elements.
Int32List getModifiedElementIds({required String modelAId, required String modelBId}) =>
    RustLib.instance.api.crateApiComparisonGetModifiedElementIds(modelAId: modelAId, modelBId: modelBId);

/// Export a CSV change report comparing two models.
String exportComparisonCsv({required String modelAId, required String modelBId}) =>
    RustLib.instance.api.crateApiComparisonExportComparisonCsv(modelAId: modelAId, modelBId: modelBId);

/// Run comparison between two models and store results in the overlay state.
/// Returns JSON summary: `{"added": N, "removed": N, "modified": N, "unchanged": N}`
String setComparisonOverlay({required String modelIdA, required String modelIdB}) =>
    RustLib.instance.api.crateApiComparisonSetComparisonOverlay(modelIdA: modelIdA, modelIdB: modelIdB);

/// Clear the comparison overlay state.
void clearComparisonOverlay() => RustLib.instance.api.crateApiComparisonClearComparisonOverlay();

/// Check if a comparison overlay is currently active.
bool isComparisonOverlayActive() => RustLib.instance.api.crateApiComparisonIsComparisonOverlayActive();

/// Get the comparison status of a specific element.
/// Returns "added", "removed", "modified", "unchanged", or "unknown".
String getComparisonElementStatus({required int elementId}) =>
    RustLib.instance.api.crateApiComparisonGetComparisonElementStatus(elementId: elementId);

/// Get the comparison overlay colors as JSON for Flutter to apply.
/// Returns: `{"added_ids": [1,2,3], "removed_ids": [4,5], "modified_ids": [6,7], "unchanged_ids": [8,9]}`
String getComparisonOverlayColors() => RustLib.instance.api.crateApiComparisonGetComparisonOverlayColors();

/// Select all elements with a given comparison status ("added", "removed", "modified").
/// Returns the count of selected elements.
BigInt navigateToComparisonGroup({required String status}) =>
    RustLib.instance.api.crateApiComparisonNavigateToComparisonGroup(status: status);

/// Basic element info for comparison results.
class ComparisonElement {
  final int elementId;
  final String globalId;
  final String name;
  final String elementType;

  const ComparisonElement({
    required this.elementId,
    required this.globalId,
    required this.name,
    required this.elementType,
  });

  @override
  int get hashCode => elementId.hashCode ^ globalId.hashCode ^ name.hashCode ^ elementType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComparisonElement &&
          runtimeType == other.runtimeType &&
          elementId == other.elementId &&
          globalId == other.globalId &&
          name == other.name &&
          elementType == other.elementType;
}

/// An element that exists in both models but has changed.
class ComparisonModification {
  final String globalId;
  final String name;
  final String elementType;
  final int oldElementId;
  final int newElementId;

  /// Human-readable descriptions of what changed.
  final List<String> changes;

  const ComparisonModification({
    required this.globalId,
    required this.name,
    required this.elementType,
    required this.oldElementId,
    required this.newElementId,
    required this.changes,
  });

  @override
  int get hashCode =>
      globalId.hashCode ^
      name.hashCode ^
      elementType.hashCode ^
      oldElementId.hashCode ^
      newElementId.hashCode ^
      changes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComparisonModification &&
          runtimeType == other.runtimeType &&
          globalId == other.globalId &&
          name == other.name &&
          elementType == other.elementType &&
          oldElementId == other.oldElementId &&
          newElementId == other.newElementId &&
          changes == other.changes;
}

/// Result of comparing two models.
class ComparisonResult {
  /// Elements present in model B but not in model A.
  final List<ComparisonElement> addedElements;

  /// Elements present in model A but not in model B.
  final List<ComparisonElement> removedElements;

  /// Elements present in both models but with differences.
  final List<ComparisonModification> modifiedElements;

  /// Number of elements that are identical in both models.
  final int unchangedCount;

  const ComparisonResult({
    required this.addedElements,
    required this.removedElements,
    required this.modifiedElements,
    required this.unchangedCount,
  });

  @override
  int get hashCode =>
      addedElements.hashCode ^ removedElements.hashCode ^ modifiedElements.hashCode ^ unchangedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComparisonResult &&
          runtimeType == other.runtimeType &&
          addedElements == other.addedElements &&
          removedElements == other.removedElements &&
          modifiedElements == other.modifiedElements &&
          unchangedCount == other.unchangedCount;
}
