// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Save current frame as PNG to the given path
Future<void> exportScreenshot({required String path}) =>
    RustLib.instance.api.crateApiExportExportScreenshot(path: path);

/// Get current frame as RGBA bytes
Uint8List getCurrentFrameRgba() => RustLib.instance.api.crateApiExportGetCurrentFrameRgba();

/// Get renderer statistics
RenderStats getRenderStats() => RustLib.instance.api.crateApiExportGetRenderStats();

/// Renderer statistics
class RenderStats {
  final double fps;
  final double frameTimeMs;
  final int triangleCount;
  final int vertexCount;
  final int elementCount;

  const RenderStats({
    required this.fps,
    required this.frameTimeMs,
    required this.triangleCount,
    required this.vertexCount,
    required this.elementCount,
  });

  @override
  int get hashCode =>
      fps.hashCode ^ frameTimeMs.hashCode ^ triangleCount.hashCode ^ vertexCount.hashCode ^ elementCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderStats &&
          runtimeType == other.runtimeType &&
          fps == other.fps &&
          frameTimeMs == other.frameTimeMs &&
          triangleCount == other.triangleCount &&
          vertexCount == other.vertexCount &&
          elementCount == other.elementCount;
}
