// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Set the directional light direction (will be normalized)
void setLightDirection({required double x, required double y, required double z}) =>
    RustLib.instance.api.crateApiLightingSetLightDirection(x: x, y: y, z: z);

/// Set the directional light color (RGB, 0.0-1.0)
void setLightColor({required double r, required double g, required double b}) =>
    RustLib.instance.api.crateApiLightingSetLightColor(r: r, g: g, b: b);

/// Set the directional light intensity (0.0+)
void setLightIntensity({required double intensity}) =>
    RustLib.instance.api.crateApiLightingSetLightIntensity(intensity: intensity);

/// Set the ambient light color (RGB, 0.0-1.0)
void setAmbientColor({required double r, required double g, required double b}) =>
    RustLib.instance.api.crateApiLightingSetAmbientColor(r: r, g: g, b: b);

/// Set the render mode
/// 0 = Shaded (default), 1 = Wireframe, 2 = X-Ray
void setRenderMode({required int mode}) => RustLib.instance.api.crateApiLightingSetRenderMode(mode: mode);

/// Get the current render mode
/// Returns: 0 = Shaded, 1 = Wireframe, 2 = X-Ray
int getRenderMode() => RustLib.instance.api.crateApiLightingGetRenderMode();

/// Check if wireframe rendering is supported on this device
bool isWireframeSupported() => RustLib.instance.api.crateApiLightingIsWireframeSupported();

/// Set element color by ID
void setElementColor({required int elementId, required int r, required int g, required int b}) =>
    RustLib.instance.api.crateApiLightingSetElementColor(elementId: elementId, r: r, g: g, b: b);

/// Reset all element colors to defaults
void resetElementColors() => RustLib.instance.api.crateApiLightingResetElementColors();

/// Color elements by type
void colorByType() => RustLib.instance.api.crateApiLightingColorByType();
