// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MeasurementType`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Start a new measurement
void startMeasurement({required String measurementType}) =>
    RustLib.instance.api.crateApiMeasurementStartMeasurement(measurementType: measurementType);

/// Add a measurement point
int addMeasurementPoint({required double x, required double y, required double z}) =>
    RustLib.instance.api.crateApiMeasurementAddMeasurementPoint(x: x, y: y, z: z);

/// Get the current measurement result
MeasurementResult getMeasurementResult() => RustLib.instance.api.crateApiMeasurementGetMeasurementResult();

/// Clear the current measurement
void clearMeasurement() => RustLib.instance.api.crateApiMeasurementClearMeasurement();

/// Get the number of measurement points
int getMeasurementPointCount() => RustLib.instance.api.crateApiMeasurementGetMeasurementPointCount();

/// Measurement point in 3D space
class MeasurementPoint {
  final double x;
  final double y;
  final double z;

  const MeasurementPoint({
    required this.x,
    required this.y,
    required this.z,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ z.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeasurementPoint && runtimeType == other.runtimeType && x == other.x && y == other.y && z == other.z;
}

/// Measurement result
class MeasurementResult {
  final String measurementType;
  final double value;
  final String unit;
  final List<MeasurementPoint> points;

  const MeasurementResult({
    required this.measurementType,
    required this.value,
    required this.unit,
    required this.points,
  });

  @override
  int get hashCode => measurementType.hashCode ^ value.hashCode ^ unit.hashCode ^ points.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeasurementResult &&
          runtimeType == other.runtimeType &&
          measurementType == other.measurementType &&
          value == other.value &&
          unit == other.unit &&
          points == other.points;
}
