// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../bim/model.dart';
import '../bim/model_registry.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Load an IFC file and parse it (backward compatible - loads as primary)
Future<ModelInfo> loadIfcFile({required String filePath}) =>
    RustLib.instance.api.crateApiModelsLoadIfcFile(filePath: filePath);

/// Get information about the currently loaded model (primary model)
ModelInfo getModelInfo() => RustLib.instance.api.crateApiModelsGetModelInfo();

/// Check if a model is currently loaded
bool isModelLoaded() => RustLib.instance.api.crateApiModelsIsModelLoaded();

/// Unload the current model and free memory (primary model)
void unloadModel() => RustLib.instance.api.crateApiModelsUnloadModel();

/// Parse IFC file content (for testing - takes content string instead of file path)
Future<ModelInfo> parseIfcContent({required String content}) =>
    RustLib.instance.api.crateApiModelsParseIfcContent(content: content);

/// Load a model with a specific ID
Future<ModelInfo> loadModel({required String modelId, required String filePath}) =>
    RustLib.instance.api.crateApiModelsLoadModel(modelId: modelId, filePath: filePath);

/// Unload a specific model by ID
void unloadModelById({required String modelId}) => RustLib.instance.api.crateApiModelsUnloadModelById(modelId: modelId);

/// List all loaded models
List<RegisteredModelInfo> listLoadedModels() => RustLib.instance.api.crateApiModelsListLoadedModels();

/// Get number of loaded models
BigInt getModelCount() => RustLib.instance.api.crateApiModelsGetModelCount();

/// Set model visibility
void setModelVisible({required String modelId, required bool visible}) =>
    RustLib.instance.api.crateApiModelsSetModelVisible(modelId: modelId, visible: visible);

/// Set the primary model
void setPrimaryModel({required String modelId}) => RustLib.instance.api.crateApiModelsSetPrimaryModel(modelId: modelId);

/// Clear all models
void clearAllModels() => RustLib.instance.api.crateApiModelsClearAllModels();
