// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../bim/model.dart';
import '../bim/model_registry.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_model_from_gltf`, `next_loading_id`, `set_loading_state`, `to_json`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LoadingState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Check the status of an async loading task.
/// Returns JSON describing the current state.
String getLoadingState({required String loadingId}) =>
    RustLib.instance.api.crateApiModelsGetLoadingState(loadingId: loadingId);

/// Cancel an async loading task (if possible).
/// Currently marks the task as failed; actual cancellation of in-flight I/O
/// is not supported by the synchronous parsing pipeline.
void cancelLoading({required String loadingId}) =>
    RustLib.instance.api.crateApiModelsCancelLoading(loadingId: loadingId);

/// List all active loading tasks as JSON array.
String listLoadingTasks() => RustLib.instance.api.crateApiModelsListLoadingTasks();

/// Load an IFC file and parse it (backward compatible - loads as primary).
/// Updates loading task state as it progresses.
Future<ModelInfo> loadIfcFile({required String filePath}) =>
    RustLib.instance.api.crateApiModelsLoadIfcFile(filePath: filePath);

/// Start loading an IFC file in the background.
/// Returns a loading ID that can be used to check progress via `get_loading_state`.
Future<String> loadIfcFileAsync({required String filePath}) =>
    RustLib.instance.api.crateApiModelsLoadIfcFileAsync(filePath: filePath);

/// Get information about the currently loaded model (primary model)
ModelInfo getModelInfo() => RustLib.instance.api.crateApiModelsGetModelInfo();

/// Check if a model is currently loaded
bool isModelLoaded() => RustLib.instance.api.crateApiModelsIsModelLoaded();

/// Unload the current model and free memory (primary model)
void unloadModel() => RustLib.instance.api.crateApiModelsUnloadModel();

/// Parse IFC file content (for testing - takes content string instead of file path)
Future<ModelInfo> parseIfcContent({required String content}) =>
    RustLib.instance.api.crateApiModelsParseIfcContent(content: content);

/// Load a model with a specific ID
Future<ModelInfo> loadModel({required String modelId, required String filePath}) =>
    RustLib.instance.api.crateApiModelsLoadModel(modelId: modelId, filePath: filePath);

/// Unload a specific model by ID
void unloadModelById({required String modelId}) => RustLib.instance.api.crateApiModelsUnloadModelById(modelId: modelId);

/// List all loaded models
List<RegisteredModelInfo> listLoadedModels() => RustLib.instance.api.crateApiModelsListLoadedModels();

/// Get number of loaded models
BigInt getModelCount() => RustLib.instance.api.crateApiModelsGetModelCount();

/// Set model visibility
void setModelVisible({required String modelId, required bool visible}) =>
    RustLib.instance.api.crateApiModelsSetModelVisible(modelId: modelId, visible: visible);

/// Set the primary model
void setPrimaryModel({required String modelId}) => RustLib.instance.api.crateApiModelsSetPrimaryModel(modelId: modelId);

/// Clear all models
void clearAllModels() => RustLib.instance.api.crateApiModelsClearAllModels();

/// Import an OBJ file and register it as a model.
Future<ModelInfo> importObjFile({required String filePath}) =>
    RustLib.instance.api.crateApiModelsImportObjFile(filePath: filePath);

/// Import a glTF JSON file and register it as a model.
Future<ModelInfo> importGltfFile({required String filePath}) =>
    RustLib.instance.api.crateApiModelsImportGltfFile(filePath: filePath);

/// Import a GLB binary file and register it as a model.
Future<ModelInfo> importGlbFile({required String filePath}) =>
    RustLib.instance.api.crateApiModelsImportGlbFile(filePath: filePath);

/// Detect the IFC schema version of a file from its content.
String detectFileSchema({required String fileContent}) =>
    RustLib.instance.api.crateApiModelsDetectFileSchema(fileContent: fileContent);
