// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ViewMode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Upload a 2D drawing/floor plan as an overlay texture
Future<void> uploadDrawingOverlay(
        {required String id, required int width, required int height, required List<int> rgbaPixels}) =>
    RustLib.instance.api
        .crateApiOverlayUploadDrawingOverlay(id: id, width: width, height: height, rgbaPixels: rgbaPixels);

/// Set overlay transform (position, scale, rotation)
void setOverlayTransform(
        {required String id,
        required double positionX,
        required double positionY,
        required double positionZ,
        required double scaleX,
        required double scaleY,
        required double rotation}) =>
    RustLib.instance.api.crateApiOverlaySetOverlayTransform(
        id: id,
        positionX: positionX,
        positionY: positionY,
        positionZ: positionZ,
        scaleX: scaleX,
        scaleY: scaleY,
        rotation: rotation);

/// Set overlay opacity (0.0 to 1.0)
void setOverlayOpacity({required String id, required double opacity}) =>
    RustLib.instance.api.crateApiOverlaySetOverlayOpacity(id: id, opacity: opacity);

/// Set overlay visibility
void setOverlayVisible({required String id, required bool visible}) =>
    RustLib.instance.api.crateApiOverlaySetOverlayVisible(id: id, visible: visible);

/// Remove an overlay
void removeOverlay({required String id}) => RustLib.instance.api.crateApiOverlayRemoveOverlay(id: id);

/// Set view mode
void setViewMode({required String mode}) => RustLib.instance.api.crateApiOverlaySetViewMode(mode: mode);

/// Get current view mode
String getViewMode() => RustLib.instance.api.crateApiOverlayGetViewMode();
