// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Get property sets for a given element ID.
/// Returns a list of property sets, each containing key-value pairs.
List<PropertySetInfo> getElementProperties({required int elementId}) =>
    RustLib.instance.api.crateApiPropertiesGetElementProperties(elementId: elementId);

/// Get property sets for an element across all visible models.
List<PropertySetInfo> getElementPropertiesAllModels({required int elementId}) =>
    RustLib.instance.api.crateApiPropertiesGetElementPropertiesAllModels(elementId: elementId);

/// Get the containing storey name for an element.
String? getElementStorey({required int elementId}) =>
    RustLib.instance.api.crateApiPropertiesGetElementStorey(elementId: elementId);

/// Get the spatial hierarchy tree (Project → Site → Building → Storey → elements).
/// Returns a flat list of nodes that can be assembled into a tree on the Dart side.
List<SpatialNode> getSpatialTree() => RustLib.instance.api.crateApiPropertiesGetSpatialTree();

/// Get material information for an element across all visible models.
MaterialData? getElementMaterial({required int elementId}) =>
    RustLib.instance.api.crateApiPropertiesGetElementMaterial(elementId: elementId);

/// Get type object information for an element across all visible models.
TypeObjectData? getElementTypeInfo({required int elementId}) =>
    RustLib.instance.api.crateApiPropertiesGetElementTypeInfo(elementId: elementId);

/// Get elements grouped by storey, as a flat map of storey_name → element_ids.
/// Elements not assigned to any storey are grouped under "Unassigned".
Map<String, Int32List> getElementsByStorey() => RustLib.instance.api.crateApiPropertiesGetElementsByStorey();

/// Material information for an element.
class MaterialData {
  final String name;
  final String? category;
  final List<MaterialLayerData> layers;

  const MaterialData({
    required this.name,
    this.category,
    required this.layers,
  });

  @override
  int get hashCode => name.hashCode ^ category.hashCode ^ layers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MaterialData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          category == other.category &&
          layers == other.layers;
}

/// A single material layer.
class MaterialLayerData {
  final String materialName;
  final double? thickness;

  const MaterialLayerData({
    required this.materialName,
    this.thickness,
  });

  @override
  int get hashCode => materialName.hashCode ^ thickness.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MaterialLayerData &&
          runtimeType == other.runtimeType &&
          materialName == other.materialName &&
          thickness == other.thickness;
}

/// A single property with name and value.
class PropertyInfo {
  final String name;
  final String value;

  const PropertyInfo({
    required this.name,
    required this.value,
  });

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PropertyInfo && runtimeType == other.runtimeType && name == other.name && value == other.value;
}

/// A property set with name and list of key-value properties.
class PropertySetInfo {
  final String name;
  final List<PropertyInfo> properties;

  const PropertySetInfo({
    required this.name,
    required this.properties,
  });

  @override
  int get hashCode => name.hashCode ^ properties.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PropertySetInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          properties == other.properties;
}

/// A node in the spatial hierarchy tree.
class SpatialNode {
  final int id;
  final String name;

  /// "Project", "Site", "Building", "Storey"
  final String nodeType;
  final int? parentId;
  final Int32List elementIds;

  const SpatialNode({
    required this.id,
    required this.name,
    required this.nodeType,
    this.parentId,
    required this.elementIds,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ nodeType.hashCode ^ parentId.hashCode ^ elementIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpatialNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          nodeType == other.nodeType &&
          parentId == other.parentId &&
          elementIds == other.elementIds;
}

/// Type object information for an element.
class TypeObjectData {
  /// Type name (e.g., "FLOOR_PLANK", "INNER_SHELL")
  final String typeName;

  /// IFC entity type (e.g., "IFCSLABTYPE", "IFCWALLTYPE")
  final String ifcType;

  /// Property sets defined on the type
  final List<PropertySetInfo> propertySets;

  const TypeObjectData({
    required this.typeName,
    required this.ifcType,
    required this.propertySets,
  });

  @override
  int get hashCode => typeName.hashCode ^ ifcType.hashCode ^ propertySets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypeObjectData &&
          runtimeType == other.runtimeType &&
          typeName == other.typeName &&
          ifcType == other.ifcType &&
          propertySets == other.propertySets;
}
