// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_area_quantity`, `is_length_quantity`, `is_volume_quantity`, `is_weight_quantity`, `try_parse_quantity_value`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UnitState`, `UnitSystem`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Set the display unit system. 0 = SI, 1 = Imperial.
void setUnitSystem({required int system}) => RustLib.instance.api.crateApiPropertiesSetUnitSystem(system: system);

/// Get the current display unit system. Returns 0 (SI) or 1 (Imperial).
int getUnitSystem() => RustLib.instance.api.crateApiPropertiesGetUnitSystem();

/// Convert a length value from IFC units to the current display units.
///
/// The conversion chain is: IFC value * length_factor -> meters -> display units.
double convertLength({required double value}) => RustLib.instance.api.crateApiPropertiesConvertLength(value: value);

/// Convert an area value from IFC units to the current display units.
double convertArea({required double value}) => RustLib.instance.api.crateApiPropertiesConvertArea(value: value);

/// Convert a volume value from IFC units to the current display units.
double convertVolume({required double value}) => RustLib.instance.api.crateApiPropertiesConvertVolume(value: value);

/// Get the label for the current length unit (e.g., "m", "mm", "ft").
String getLengthUnitLabel() => RustLib.instance.api.crateApiPropertiesGetLengthUnitLabel();

/// Get the label for the current area unit (e.g., "m\u{b2}", "ft\u{b2}").
String getAreaUnitLabel() => RustLib.instance.api.crateApiPropertiesGetAreaUnitLabel();

/// Get the label for the current volume unit (e.g., "m\u{b3}", "ft\u{b3}").
String getVolumeUnitLabel() => RustLib.instance.api.crateApiPropertiesGetVolumeUnitLabel();

/// Detect IFC units from the loaded model's entity map and set the conversion factors.
///
/// Reads IFCUNITASSIGNMENT entities to determine the length, area, and volume
/// conversion factors. Returns a human-readable description of the detected units
/// (e.g., "Length: mm, Area: mm\u{b2}, Volume: mm\u{b3}").
String detectIfcUnits() => RustLib.instance.api.crateApiPropertiesDetectIfcUnits();

/// Get property sets for a given element ID.
/// Returns a list of property sets, each containing key-value pairs.
List<PropertySetInfo> getElementProperties({required int elementId}) =>
    RustLib.instance.api.crateApiPropertiesGetElementProperties(elementId: elementId);

/// Get property sets for an element across all visible models.
List<PropertySetInfo> getElementPropertiesAllModels({required int elementId}) =>
    RustLib.instance.api.crateApiPropertiesGetElementPropertiesAllModels(elementId: elementId);

/// Get the containing storey name for an element.
String? getElementStorey({required int elementId}) =>
    RustLib.instance.api.crateApiPropertiesGetElementStorey(elementId: elementId);

/// Get the spatial hierarchy tree (Project → Site → Building → Storey → elements).
/// Returns a flat list of nodes that can be assembled into a tree on the Dart side.
List<SpatialNode> getSpatialTree() => RustLib.instance.api.crateApiPropertiesGetSpatialTree();

/// Get material information for an element across all visible models.
MaterialData? getElementMaterial({required int elementId}) =>
    RustLib.instance.api.crateApiPropertiesGetElementMaterial(elementId: elementId);

/// Get type object information for an element across all visible models.
TypeObjectData? getElementTypeInfo({required int elementId}) =>
    RustLib.instance.api.crateApiPropertiesGetElementTypeInfo(elementId: elementId);

/// Get quantity summary grouped by element type.
List<QuantitySummary> getQuantitySummaryByType() => RustLib.instance.api.crateApiPropertiesGetQuantitySummaryByType();

/// Get quantity summary grouped by storey.
List<QuantitySummary> getQuantitySummaryByStorey() =>
    RustLib.instance.api.crateApiPropertiesGetQuantitySummaryByStorey();

/// Get elements grouped by storey, as a flat map of storey_name → element_ids.
/// Elements not assigned to any storey are grouped under "Unassigned".
Map<String, Int32List> getElementsByStorey() => RustLib.instance.api.crateApiPropertiesGetElementsByStorey();

/// Get elements grouped by element type, as a flat map of type_name -> element_ids.
///
/// Similar to `get_elements_by_storey()` but groups by element type instead of storey.
/// Returns a map like: { "Wall": [1, 5, 9], "Slab": [2, 6], "Door": [3, 7] }
Map<String, Int32List> getElementsGroupedByType() => RustLib.instance.api.crateApiPropertiesGetElementsGroupedByType();

/// Get the IFC map conversion (georeferencing) data as JSON, if present.
///
/// Returns `Ok(Some(json))` if IFCMAPCONVERSION data was found in the model,
/// or `Ok(None)` if no georeferencing data is present.
///
/// The JSON includes: eastings, northings, orthogonal_height, x_axis_abscissa,
/// x_axis_ordinate, scale, crs_name, crs_description, geodetic_datum,
/// vertical_datum, map_projection, map_zone.
String? getMapConversion() => RustLib.instance.api.crateApiPropertiesGetMapConversion();

/// Material information for an element.
class MaterialData {
  final String name;
  final String? category;
  final List<MaterialLayerData> layers;

  const MaterialData({
    required this.name,
    this.category,
    required this.layers,
  });

  @override
  int get hashCode => name.hashCode ^ category.hashCode ^ layers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MaterialData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          category == other.category &&
          layers == other.layers;
}

/// A single material layer.
class MaterialLayerData {
  final String materialName;
  final double? thickness;

  const MaterialLayerData({
    required this.materialName,
    this.thickness,
  });

  @override
  int get hashCode => materialName.hashCode ^ thickness.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MaterialLayerData &&
          runtimeType == other.runtimeType &&
          materialName == other.materialName &&
          thickness == other.thickness;
}

/// A single property with name and value.
class PropertyInfo {
  final String name;
  final String value;

  const PropertyInfo({
    required this.name,
    required this.value,
  });

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PropertyInfo && runtimeType == other.runtimeType && name == other.name && value == other.value;
}

/// A property set with name and list of key-value properties.
class PropertySetInfo {
  final String name;
  final List<PropertyInfo> properties;

  const PropertySetInfo({
    required this.name,
    required this.properties,
  });

  @override
  int get hashCode => name.hashCode ^ properties.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PropertySetInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          properties == other.properties;
}

/// Quantity summary entry (aggregated by type or storey)
class QuantitySummary {
  final String groupName;
  final int elementCount;
  final double totalArea;
  final double totalVolume;
  final double totalLength;
  final double totalWeight;

  const QuantitySummary({
    required this.groupName,
    required this.elementCount,
    required this.totalArea,
    required this.totalVolume,
    required this.totalLength,
    required this.totalWeight,
  });

  @override
  int get hashCode =>
      groupName.hashCode ^
      elementCount.hashCode ^
      totalArea.hashCode ^
      totalVolume.hashCode ^
      totalLength.hashCode ^
      totalWeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuantitySummary &&
          runtimeType == other.runtimeType &&
          groupName == other.groupName &&
          elementCount == other.elementCount &&
          totalArea == other.totalArea &&
          totalVolume == other.totalVolume &&
          totalLength == other.totalLength &&
          totalWeight == other.totalWeight;
}

/// A node in the spatial hierarchy tree.
class SpatialNode {
  final int id;
  final String name;

  /// "Project", "Site", "Building", "Storey"
  final String nodeType;
  final int? parentId;
  final Int32List elementIds;

  const SpatialNode({
    required this.id,
    required this.name,
    required this.nodeType,
    this.parentId,
    required this.elementIds,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ nodeType.hashCode ^ parentId.hashCode ^ elementIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpatialNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          nodeType == other.nodeType &&
          parentId == other.parentId &&
          elementIds == other.elementIds;
}

/// Type object information for an element.
class TypeObjectData {
  /// Type name (e.g., "FLOOR_PLANK", "INNER_SHELL")
  final String typeName;

  /// IFC entity type (e.g., "IFCSLABTYPE", "IFCWALLTYPE")
  final String ifcType;

  /// Property sets defined on the type
  final List<PropertySetInfo> propertySets;

  const TypeObjectData({
    required this.typeName,
    required this.ifcType,
    required this.propertySets,
  });

  @override
  int get hashCode => typeName.hashCode ^ ifcType.hashCode ^ propertySets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TypeObjectData &&
          runtimeType == other.runtimeType &&
          typeName == other.typeName &&
          ifcType == other.ifcType &&
          propertySets == other.propertySets;
}
