// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `palette_color`

/// Test renderer initialization
Future<String> testRendererInit() => RustLib.instance.api.crateApiRenderingTestRendererInit();

/// Initialize the 3D renderer with given dimensions
Future<String> initRenderer({required int width, required int height}) =>
    RustLib.instance.api.crateApiRenderingInitRenderer(width: width, height: height);

/// Render a frame and return RGBA pixel data
Uint8List renderFrame() => RustLib.instance.api.crateApiRenderingRenderFrame();

/// Check if renderer is initialized
bool isRendererInitialized() => RustLib.instance.api.crateApiRenderingIsRendererInitialized();

/// Load the currently loaded BIM model into the renderer (primary model)
String loadModelIntoRenderer() => RustLib.instance.api.crateApiRenderingLoadModelIntoRenderer();

/// Load all visible models into the renderer
String loadAllModelsIntoRenderer() => RustLib.instance.api.crateApiRenderingLoadAllModelsIntoRenderer();

/// Reload model mesh with current visibility and highlight settings (primary model)
String reloadModelMesh() => RustLib.instance.api.crateApiRenderingReloadModelMesh();

/// Reload all visible models with current visibility and highlight settings
String reloadAllModelsMesh() => RustLib.instance.api.crateApiRenderingReloadAllModelsMesh();
