// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ifc_to_yup_bounds`, `ifc_to_yup_point`, `ifc_to_yup_vertices`, `palette_color`

/// Test renderer initialization
Future<String> testRendererInit() => RustLib.instance.api.crateApiRenderingTestRendererInit();

/// Initialize the 3D renderer with given dimensions
Future<String> initRenderer({required int width, required int height}) =>
    RustLib.instance.api.crateApiRenderingInitRenderer(width: width, height: height);

/// Render a frame and return RGBA pixel data
Uint8List renderFrame() => RustLib.instance.api.crateApiRenderingRenderFrame();

/// Check if renderer is initialized
bool isRendererInitialized() => RustLib.instance.api.crateApiRenderingIsRendererInitialized();

/// Set interaction active state for FastNav adaptive quality.
/// Call with true when camera interaction starts, false when it ends.
/// During interaction, expensive post-processing (SSAO, edge rendering) is skipped.
void setInteractionActive({required bool active}) =>
    RustLib.instance.api.crateApiRenderingSetInteractionActive(active: active);

/// Get the scene bounding box in world coordinates (Y-up).
/// Returns (min_x, min_y, min_z, max_x, max_y, max_z) or error if no geometry.
Float32List getSceneBounds() => RustLib.instance.api.crateApiRenderingGetSceneBounds();

/// Load the currently loaded BIM model into the renderer (primary model)
String loadModelIntoRenderer() => RustLib.instance.api.crateApiRenderingLoadModelIntoRenderer();

/// Load all visible models into the renderer
String loadAllModelsIntoRenderer() => RustLib.instance.api.crateApiRenderingLoadAllModelsIntoRenderer();

/// Reload model mesh with current visibility and highlight settings (primary model)
String reloadModelMesh() => RustLib.instance.api.crateApiRenderingReloadModelMesh();

/// Reload all visible models with current visibility and highlight settings
String reloadAllModelsMesh() => RustLib.instance.api.crateApiRenderingReloadAllModelsMesh();
