// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SectionPlane`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Set the section plane
void setSectionPlane(
        {required double originX,
        required double originY,
        required double originZ,
        required double normalX,
        required double normalY,
        required double normalZ}) =>
    RustLib.instance.api.crateApiSectionSetSectionPlane(
        originX: originX, originY: originY, originZ: originZ, normalX: normalX, normalY: normalY, normalZ: normalZ);

/// Enable or disable the section plane
void setSectionPlaneEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiSectionSetSectionPlaneEnabled(enabled: enabled);

/// Clear the section plane
void clearSectionPlane() => RustLib.instance.api.crateApiSectionClearSectionPlane();

/// Check if section plane is active
bool isSectionPlaneActive() => RustLib.instance.api.crateApiSectionIsSectionPlaneActive();

/// Set section plane from axis (X=0, Y=1, Z=2) and position
void setSectionPlaneFromAxis({required int axis, required double position}) =>
    RustLib.instance.api.crateApiSectionSetSectionPlaneFromAxis(axis: axis, position: position);
