// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../bim/entities.dart';
import '../bim/geometry.dart';
import '../bim/model.dart';
import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dms_to_decimal`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Pick element at screen coordinates (searches all visible models)
ElementInfo? pickElement({required double screenX, required double screenY}) =>
    RustLib.instance.api.crateApiSelectionPickElement(screenX: screenX, screenY: screenY);

/// Get all elements in the model (primary model)
List<ElementInfo> getAllElements() => RustLib.instance.api.crateApiSelectionGetAllElements();

/// Get all elements from all visible models
List<ElementInfo> getAllElementsFromAllModels() => RustLib.instance.api.crateApiSelectionGetAllElementsFromAllModels();

/// Get element count by type (primary model)
Map<String, BigInt> getElementCounts() => RustLib.instance.api.crateApiSelectionGetElementCounts();

/// Set visibility for an element type
void setElementTypeVisible({required String elementType, required bool visible}) =>
    RustLib.instance.api.crateApiSelectionSetElementTypeVisible(elementType: elementType, visible: visible);

/// Check if an element type is visible
bool isElementTypeVisible({required String elementType}) =>
    RustLib.instance.api.crateApiSelectionIsElementTypeVisible(elementType: elementType);

/// Get all hidden element types
List<String> getHiddenElementTypes() => RustLib.instance.api.crateApiSelectionGetHiddenElementTypes();

/// Isolate a storey — hide all elements NOT on the given storey.
/// Call reload_all_models_mesh() after this to apply.
int isolateStorey({required String storeyName}) =>
    RustLib.instance.api.crateApiSelectionIsolateStorey(storeyName: storeyName);

/// Show all storeys (clear storey isolation).
/// Call reload_all_models_mesh() after this to apply.
void showAllStoreys() => RustLib.instance.api.crateApiSelectionShowAllStoreys();

/// Get the currently isolated storey name, or null if all visible.
String? getIsolatedStorey() => RustLib.instance.api.crateApiSelectionGetIsolatedStorey();

/// Set the color visualization mode.
/// 0 = Normal, 1 = By Type, 2 = By Storey, 3 = By Material
/// Call reload_all_models_mesh() after this to apply.
void setColorMode({required int mode}) => RustLib.instance.api.crateApiSelectionSetColorMode(mode: mode);

/// Get the current color mode.
/// Returns: 0 = Normal, 1 = By Type, 2 = By Storey, 3 = By Material
int getColorMode() => RustLib.instance.api.crateApiSelectionGetColorMode();

/// Set the selected element for highlighting
void setSelectedElement({int? elementId}) =>
    RustLib.instance.api.crateApiSelectionSetSelectedElement(elementId: elementId);

/// Get all grid lines from all visible models
List<GridLine> getGridLines() => RustLib.instance.api.crateApiSelectionGetGridLines();

/// Check if grid is visible
bool isGridVisible() => RustLib.instance.api.crateApiSelectionIsGridVisible();

/// Set grid visibility
void setGridVisible({required bool visible}) => RustLib.instance.api.crateApiSelectionSetGridVisible(visible: visible);

/// Toggle grid visibility
bool toggleGridVisible() => RustLib.instance.api.crateApiSelectionToggleGridVisible();

/// Get grid line count
BigInt getGridLineCount() => RustLib.instance.api.crateApiSelectionGetGridLineCount();

/// Get georeferencing data from the primary model's site
GeoReference? getGeoReference() => RustLib.instance.api.crateApiSelectionGetGeoReference();

/// Georeferencing data from IFC site
class GeoReference {
  final double latitude;
  final double longitude;
  final double rotation;
  final double width;
  final double depth;
  final String? siteName;

  const GeoReference({
    required this.latitude,
    required this.longitude,
    required this.rotation,
    required this.width,
    required this.depth,
    this.siteName,
  });

  @override
  int get hashCode =>
      latitude.hashCode ^ longitude.hashCode ^ rotation.hashCode ^ width.hashCode ^ depth.hashCode ^ siteName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeoReference &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          rotation == other.rotation &&
          width == other.width &&
          depth == other.depth &&
          siteName == other.siteName;
}
