// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `draw_ranges_from_mesh`, `instances_from_mesh`, `new`, `with_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AppState`, `PickAccelerator`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `build`, `empty`, `ensure_bvh_fresh`, `mark_bvh_dirty`, `rebuild_pick_bvh`, `renderer`

/// Color-by visualization mode
enum ColorMode {
  normal,
  byType,
  byStorey,
  byMaterial,
  ;

  static Future<ColorMode> default_() => RustLib.instance.api.crateApiStateColorModeDefault();
}
