// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the BIM viewer engine
/// This should be called once when the app starts
String initialize() => RustLib.instance.api.crateApiSystemInitialize();

/// Get the library version
String getVersion() => RustLib.instance.api.crateApiSystemGetVersion();

/// Get system information for debugging
String getSystemInfo() => RustLib.instance.api.crateApiSystemGetSystemInfo();

/// Test async functionality
Future<String> testAsync() => RustLib.instance.api.crateApiSystemTestAsync();

/// Test error handling across FFI
String testErrorHandling({required bool shouldFail}) =>
    RustLib.instance.api.crateApiSystemTestErrorHandling(shouldFail: shouldFail);
