// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the BIM viewer engine
/// This should be called once when the app starts
String initialize() => RustLib.instance.api.crateApiInitialize();

/// Get the library version
String getVersion() => RustLib.instance.api.crateApiGetVersion();

/// Get system information for debugging
String getSystemInfo() => RustLib.instance.api.crateApiGetSystemInfo();

/// Test async functionality
/// This demonstrates that async Rust functions work correctly across FFI
Future<String> testAsync() => RustLib.instance.api.crateApiTestAsync();

/// Test error handling across FFI
/// Returns a Result to demonstrate error propagation
String testErrorHandling({required bool shouldFail}) =>
    RustLib.instance.api.crateApiTestErrorHandling(shouldFail: shouldFail);
