// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'bim/model.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the BIM viewer engine
/// This should be called once when the app starts
String initialize() => RustLib.instance.api.crateApiInitialize();

/// Get the library version
String getVersion() => RustLib.instance.api.crateApiGetVersion();

/// Get system information for debugging
String getSystemInfo() => RustLib.instance.api.crateApiGetSystemInfo();

/// Test async functionality
/// This demonstrates that async Rust functions work correctly across FFI
Future<String> testAsync() => RustLib.instance.api.crateApiTestAsync();

/// Test error handling across FFI
/// Returns a Result to demonstrate error propagation
String testErrorHandling({required bool shouldFail}) =>
    RustLib.instance.api.crateApiTestErrorHandling(shouldFail: shouldFail);

/// Load an IFC file and parse it
/// This is async because file I/O can be slow
Future<ModelInfo> loadIfcFile({required String filePath}) =>
    RustLib.instance.api.crateApiLoadIfcFile(filePath: filePath);

/// Get information about the currently loaded model
ModelInfo getModelInfo() => RustLib.instance.api.crateApiGetModelInfo();

/// Check if a model is currently loaded
bool isModelLoaded() => RustLib.instance.api.crateApiIsModelLoaded();

/// Unload the current model and free memory
void unloadModel() => RustLib.instance.api.crateApiUnloadModel();

/// Parse IFC file content (for testing - takes content string instead of file path)
Future<ModelInfo> parseIfcContent({required String content}) =>
    RustLib.instance.api.crateApiParseIfcContent(content: content);

/// Test renderer initialization
/// This initializes the wgpu graphics backend (headless for now)
Future<String> testRendererInit() => RustLib.instance.api.crateApiTestRendererInit();
