// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'bvh.freezed.dart';

@freezed
sealed class BvhNode with _$BvhNode {
  const BvhNode._();

  const factory BvhNode.leaf({
    required F32Array3 min,
    required F32Array3 max,
    required BigInt elementIndex,
  }) = BvhNode_Leaf;
  const factory BvhNode.internal({
    required F32Array3 min,
    required F32Array3 max,
    required BvhNode left,
    required BvhNode right,
  }) = BvhNode_Internal;
}
