// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Represents a parsed grid line for rendering
class GridLine {
  final String tag;
  final F32Array3 start;
  final F32Array3 end;
  final bool isUAxis;

  const GridLine({
    required this.tag,
    required this.start,
    required this.end,
    required this.isUAxis,
  });

  @override
  int get hashCode => tag.hashCode ^ start.hashCode ^ end.hashCode ^ isUAxis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GridLine &&
          runtimeType == other.runtimeType &&
          tag == other.tag &&
          start == other.start &&
          end == other.end &&
          isUAxis == other.isUAxis;
}
