// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Information about a model in the registry (for Flutter)
class RegisteredModelInfo {
  final String id;
  final String name;
  final String? filePath;
  final bool visible;
  final bool isPrimary;
  final ModelInfo modelInfo;

  const RegisteredModelInfo({
    required this.id,
    required this.name,
    this.filePath,
    required this.visible,
    required this.isPrimary,
    required this.modelInfo,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ filePath.hashCode ^ visible.hashCode ^ isPrimary.hashCode ^ modelInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegisteredModelInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          filePath == other.filePath &&
          visible == other.visible &&
          isPrimary == other.isPrimary &&
          modelInfo == other.modelInfo;
}
