// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'geometry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Element information for selection/properties
class ElementInfo {
  final int id;
  final String elementType;
  final String name;
  final String globalId;
  final BoundingBox bounds;
  final int triangleStart;
  final int triangleCount;

  const ElementInfo({
    required this.id,
    required this.elementType,
    required this.name,
    required this.globalId,
    required this.bounds,
    required this.triangleStart,
    required this.triangleCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      elementType.hashCode ^
      name.hashCode ^
      globalId.hashCode ^
      bounds.hashCode ^
      triangleStart.hashCode ^
      triangleCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ElementInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          elementType == other.elementType &&
          name == other.name &&
          globalId == other.globalId &&
          bounds == other.bounds &&
          triangleStart == other.triangleStart &&
          triangleCount == other.triangleCount;
}

/// Model information (for Flutter)
class ModelInfo {
  final String projectName;
  final String buildingName;
  final String siteName;
  final ModelStats stats;

  const ModelInfo({
    required this.projectName,
    required this.buildingName,
    required this.siteName,
    required this.stats,
  });

  @override
  int get hashCode => projectName.hashCode ^ buildingName.hashCode ^ siteName.hashCode ^ stats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelInfo &&
          runtimeType == other.runtimeType &&
          projectName == other.projectName &&
          buildingName == other.buildingName &&
          siteName == other.siteName &&
          stats == other.stats;
}

/// Model statistics
class ModelStats {
  final BigInt totalEntities;
  final BigInt walls;
  final BigInt slabs;
  final BigInt columns;
  final BigInt beams;
  final BigInt doors;
  final BigInt windows;
  final BigInt storeys;

  const ModelStats({
    required this.totalEntities,
    required this.walls,
    required this.slabs,
    required this.columns,
    required this.beams,
    required this.doors,
    required this.windows,
    required this.storeys,
  });

  @override
  int get hashCode =>
      totalEntities.hashCode ^
      walls.hashCode ^
      slabs.hashCode ^
      columns.hashCode ^
      beams.hashCode ^
      doors.hashCode ^
      windows.hashCode ^
      storeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelStats &&
          runtimeType == other.runtimeType &&
          totalEntities == other.totalEntities &&
          walls == other.walls &&
          slabs == other.slabs &&
          columns == other.columns &&
          beams == other.beams &&
          doors == other.doors &&
          windows == other.windows &&
          storeys == other.storeys;
}
